# poetry install --extras "ui llms-llama-cpp vector-stores-qdrant embeddings-huggingface"
server:
  env_name: ${APP_ENV:local}

llm:
  mode: llamacpp
  # Should be matching the selected model
  max_new_tokens: 512
  context_window: 3900
  tokenizer: meta-llama/Meta-Llama-3.1-8B-Instruct
  prompt_style: "llama3"

llamacpp:
  llm_hf_repo_id: lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF
  llm_hf_model_file: Meta-Llama-3.1-8B-Instruct-Q8_0.gguf

embedding:
  mode: huggingface

huggingface:
  embedding_hf_model_name: dunzhang/stella_en_1.5B_v5

vectorstore:
  database: qdrant

qdrant:
  path: local_data/private_gpt/qdrant
